# Generated by Django 5.2.11 on 2026-02-08 05:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('topics_count', models.IntegerField(default=0)),
                ('clusters_count', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TrendCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='trends_viewer.collectionrun')),
            ],
            options={
                'ordering': ['rank'],
                'unique_together': {('collection_run', 'rank')},
            },
        ),
        migrations.CreateModel(
            name='CollectedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('google_news', 'Google News')], max_length=50)),
                ('url', models.URLField(max_length=1000)),
                ('timestamp', models.DateTimeField()),
                ('upvotes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('collection_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='trends_viewer.collectionrun')),
                ('cluster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topics', to='trends_viewer.trendcluster')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
