# Generated by Django 6.0.2 on 2026-02-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedtopic',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectedtopic',
            name='full_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='collectedtopic',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='collectedtopic',
            name='title_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='trendcluster',
            name='full_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trendcluster',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='trendcluster',
            name='title_summary',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
