# Generated by Django 5.2.11 on 2026-02-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_viewer', '0002_collectedtopic_content_collectedtopic_full_summary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectedtopic',
            name='source',
            field=models.CharField(max_length=50),
        ),
    ]
