# Generated by Django 6.0.2 on 2026-02-12 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_viewer', '0003_alter_collectedtopic_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique name for this source', max_length=100, unique=True)),
                ('source_type', models.CharField(choices=[('reddit', 'Reddit'), ('hackernews', 'Hacker News'), ('twitter', 'Twitter/X'), ('youtube', 'YouTube'), ('google_news', 'Google News'), ('bbc', 'BBC News'), ('reuters', 'Reuters'), ('ap_news', 'AP News'), ('al_jazeera', 'Al Jazeera'), ('guardian', 'The Guardian'), ('rss', 'RSS Feed'), ('custom', 'Custom Plugin'), ('demo', 'Demo/Test')], help_text='Type of data source', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this source collects')),
                ('url', models.URLField(blank=True, help_text='Source URL (for RSS, API endpoints, etc.)', max_length=1000)),
                ('enabled', models.BooleanField(default=True, help_text='Enable/disable collection from this source')),
                ('schedule', models.CharField(default='0 */4 * * *', help_text="Cron expression for collection schedule (e.g., '0 */4 * * *' for every 4 hours)", max_length=50)),
                ('collection_interval_hours', models.IntegerField(default=4, help_text='Alternative: Collection interval in hours (if not using cron)')),
                ('rate_limit', models.IntegerField(blank=True, help_text='Maximum requests per hour (null = unlimited)', null=True)),
                ('timeout_seconds', models.IntegerField(default=30, help_text='Timeout for requests in seconds')),
                ('retry_count', models.IntegerField(default=3, help_text='Number of retries on failure')),
                ('backoff_multiplier', models.FloatField(default=2.0, help_text='Exponential backoff multiplier for retries')),
                ('api_key_encrypted', models.BinaryField(blank=True, help_text='Encrypted API key for authenticated sources', null=True)),
                ('oauth_config', models.JSONField(blank=True, default=dict, help_text='OAuth configuration (client_id, client_secret, tokens, etc.)')),
                ('custom_headers', models.JSONField(blank=True, default=dict, help_text='Custom HTTP headers for requests')),
                ('category_filters', models.JSONField(blank=True, default=list, help_text='List of allowed categories (empty = all categories)')),
                ('keyword_filters', models.JSONField(blank=True, default=dict, help_text="Keyword filters: {'include': ['keyword1'], 'exclude': ['keyword2']}")),
                ('language', models.CharField(default='en', help_text="Target language code (ISO 639-1, e.g., 'en', 'es', 'ja')", max_length=10)),
                ('content_filters', models.JSONField(blank=True, default=dict, help_text='Advanced content filters (min_length, max_length, etc.)')),
                ('plugin_code', models.TextField(blank=True, help_text='Python code for custom collector plugin (must inherit from CollectorPlugin)')),
                ('config_json', models.JSONField(blank=True, default=dict, help_text='Additional source-specific configuration')),
                ('health_status', models.CharField(choices=[('unknown', 'Unknown'), ('healthy', 'Healthy'), ('warning', 'Warning'), ('unhealthy', 'Unhealthy')], default='unknown', help_text='Current health status of this source', max_length=20)),
                ('last_collection', models.DateTimeField(blank=True, help_text='Timestamp of last successful collection', null=True)),
                ('last_error', models.TextField(blank=True, help_text='Last error message (if any)')),
                ('consecutive_failures', models.IntegerField(default=0, help_text='Number of consecutive collection failures')),
                ('total_collections', models.IntegerField(default=0, help_text='Total number of collection runs')),
                ('successful_collections', models.IntegerField(default=0, help_text='Number of successful collection runs')),
                ('total_items_collected', models.IntegerField(default=0, help_text='Total number of items collected from this source')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='User who created this source', max_length=100)),
            ],
            options={
                'verbose_name': 'Crawler Source',
                'verbose_name_plural': 'Crawler Sources',
                'ordering': ['name'],
            },
        ),
    ]
