# Generated by Django 5.2.11 on 2026-02-13 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends_viewer", "0005_user_preferences"),
    ]

    operations = [
        migrations.CreateModel(
            name="TranslatedContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_text_hash",
                    models.CharField(
                        help_text="MD5 hash of source text for deduplication",
                        max_length=32,
                    ),
                ),
                (
                    "source_language",
                    models.CharField(
                        help_text="Source language code (e.g., 'en', 'zh', 'auto')",
                        max_length=10,
                    ),
                ),
                (
                    "target_language",
                    models.CharField(
                        help_text="Target language code (e.g., 'en', 'zh', 'es')",
                        max_length=10,
                    ),
                ),
                ("translated_text", models.TextField(help_text="The translated text")),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("libretranslate", "LibreTranslate"),
                            ("openai", "OpenAI"),
                            ("deepl", "DeepL"),
                            ("google", "Google Translate"),
                            ("other", "Other"),
                        ],
                        default="libretranslate",
                        help_text="Translation provider used",
                        max_length=20,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="When this translation was first cached",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="When this translation was last updated",
                    ),
                ),
            ],
            options={
                "verbose_name": "Translated Content",
                "verbose_name_plural": "Translated Contents",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["source_text_hash", "target_language"],
                        name="trends_view_source__4e3634_idx",
                    ),
                    models.Index(
                        fields=["target_language", "created_at"],
                        name="trends_view_target__2ad6ab_idx",
                    ),
                    models.Index(
                        fields=["provider", "created_at"],
                        name="trends_view_provide_f31d4a_idx",
                    ),
                ],
                "unique_together": {
                    ("source_text_hash", "source_language", "target_language")
                },
            },
        ),
    ]
