# Generated by Django 5.2.11 on 2026-02-13 01:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends_viewer", "0006_translatedcontent"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "summarization_provider",
                    models.CharField(
                        choices=[
                            (
                                "free",
                                "Free NLP Tools (Default) - Works offline, zero cost",
                            ),
                            ("openai", "OpenAI GPT - Paid API, high quality"),
                            ("anthropic", "Anthropic Claude - Paid API, high quality"),
                        ],
                        default="free",
                        help_text="Summarization service to use. Free tools work offline with no API costs.",
                        max_length=20,
                        verbose_name="Summarization Provider",
                    ),
                ),
                (
                    "free_summarization_algorithm",
                    models.CharField(
                        choices=[
                            (
                                "textrank",
                                "TextRank - Graph-based ranking (recommended)",
                            ),
                            ("lexrank", "LexRank - Graph-based with cosine similarity"),
                            ("lsa", "LSA - Latent Semantic Analysis"),
                            ("luhn", "Luhn - Word frequency based (fastest)"),
                            ("kl", "KL - Kullback-Leibler divergence"),
                        ],
                        default="textrank",
                        help_text="Algorithm to use when free summarization is selected",
                        max_length=20,
                        verbose_name="Free NLP Algorithm",
                    ),
                ),
                (
                    "max_summary_length",
                    models.IntegerField(
                        default=200,
                        help_text="Maximum characters in full_summary field",
                        validators=[
                            django.core.validators.MinValueValidator(50),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                        verbose_name="Maximum Summary Length",
                    ),
                ),
                (
                    "title_summary_length",
                    models.IntegerField(
                        default=80,
                        help_text="Maximum characters in title_summary field",
                        validators=[
                            django.core.validators.MinValueValidator(20),
                            django.core.validators.MaxValueValidator(200),
                        ],
                        verbose_name="Title Summary Length",
                    ),
                ),
                (
                    "key_points_count",
                    models.IntegerField(
                        default=5,
                        help_text="Number of key points to extract per topic",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                        verbose_name="Key Points Count",
                    ),
                ),
                (
                    "openai_model",
                    models.CharField(
                        blank=True,
                        default="gpt-4-turbo",
                        help_text="OpenAI model to use (e.g., gpt-4-turbo, gpt-3.5-turbo)",
                        max_length=50,
                        verbose_name="OpenAI Model",
                    ),
                ),
                (
                    "openai_temperature",
                    models.FloatField(
                        default=0.7,
                        help_text="Temperature for OpenAI generation (0=deterministic, 2=creative)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(2.0),
                        ],
                        verbose_name="OpenAI Temperature",
                    ),
                ),
                (
                    "anthropic_model",
                    models.CharField(
                        blank=True,
                        default="claude-3-sonnet-20240229",
                        help_text="Anthropic model to use (e.g., claude-3-sonnet, claude-3-opus)",
                        max_length=50,
                        verbose_name="Anthropic Model",
                    ),
                ),
                (
                    "batch_size",
                    models.IntegerField(
                        default=10,
                        help_text="Number of items to process in parallel",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Batch Processing Size",
                    ),
                ),
                (
                    "enable_summarization_cache",
                    models.BooleanField(
                        default=True,
                        help_text="Cache generated summaries to avoid re-processing",
                        verbose_name="Enable Summary Caching",
                    ),
                ),
                (
                    "estimated_monthly_api_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        editable=False,
                        help_text="Estimated monthly cost based on current provider (auto-calculated)",
                        max_digits=10,
                        verbose_name="Estimated Monthly Cost (USD)",
                    ),
                ),
                (
                    "total_summaries_generated",
                    models.IntegerField(
                        default=0,
                        editable=False,
                        help_text="Total summaries generated since last reset",
                        verbose_name="Total Summaries Generated",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Updated"),
                ),
                (
                    "updated_by",
                    models.CharField(
                        blank=True,
                        help_text="Username of last person to update settings",
                        max_length=100,
                        verbose_name="Updated By",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Internal notes about current configuration",
                        verbose_name="Configuration Notes",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
                "db_table": "system_settings",
            },
        ),
    ]
