# Generated by Django 6.0.2 on 2026-02-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_viewer', '0007_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectedtopic',
            name='source_name',
            field=models.CharField(blank=True, help_text="Display name for the source (e.g., 'Wenxuecity News', 'BBC', 'Google News')", max_length=100),
        ),
    ]
