# Generated by Django 5.2.11 on 2026-02-13 11:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends_viewer", "0008_collectedtopic_source_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="data_retention_days",
            field=models.IntegerField(
                default=7,
                help_text="Automatically delete collection runs older than N days (default: 7)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(365),
                ],
                verbose_name="Data Retention Period (Days)",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="enable_auto_cleanup",
            field=models.BooleanField(
                default=True,
                help_text="Automatically clean up old data daily at 3:00 AM",
                verbose_name="Enable Automatic Cleanup",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="last_cleanup_at",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="Timestamp of last successful cleanup operation",
                null=True,
                verbose_name="Last Cleanup Time",
            ),
        ),
        migrations.AddField(
            model_name="systemsettings",
            name="total_records_cleaned",
            field=models.IntegerField(
                default=0,
                editable=False,
                help_text="Total collection runs deleted since installation",
                verbose_name="Total Records Cleaned",
            ),
        ),
    ]
