# Generated by Django 6.0.2 on 2026-02-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_viewer', '0009_systemsettings_data_retention_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trendcluster',
            name='full_summary',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='trendcluster',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese (中文)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('de', 'German (Deutsch)'), ('ja', 'Japanese (日本語)'), ('ko', 'Korean (한국어)'), ('pt', 'Portuguese (Português)'), ('ru', 'Russian (Русский)'), ('ar', 'Arabic (العربية)'), ('it', 'Italian (Italiano)'), ('hi', 'Hindi (हिन्दी)')], default='en', help_text='Primary language of this trend content', max_length=10),
        ),
        migrations.AlterField(
            model_name='trendcluster',
            name='title_summary',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
