# Generated by Django 6.0.2 on 2026-02-13 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trends_viewer', '0010_alter_trendcluster_full_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendTranslationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text="Target language code (e.g., 'zh', 'es', 'fr')", max_length=10)),
                ('translated', models.BooleanField(default=False, help_text='Whether this trend has been fully translated to this language')),
                ('translated_at', models.DateTimeField(blank=True, help_text='When the translation was completed', null=True)),
                ('translation_cost', models.DecimalField(decimal_places=4, default=0, help_text='Estimated API cost for this translation in USD', max_digits=10)),
                ('topics_count', models.IntegerField(default=0, help_text='Number of topics translated')),
                ('trend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translation_statuses', to='trends_viewer.trendcluster')),
            ],
            options={
                'verbose_name': 'Trend Translation Status',
                'verbose_name_plural': 'Trend Translation Statuses',
                'db_table': 'trends_viewer_trendtranslationstatus',
                'indexes': [models.Index(fields=['language', 'translated'], name='trends_view_languag_b77714_idx'), models.Index(fields=['translated_at'], name='trends_view_transla_e01130_idx')],
                'unique_together': {('trend', 'language')},
            },
        ),
    ]
