# Generated by Django 5.2.11 on 2026-02-13 20:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trends_viewer", "0011_trendtranslationstatus"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemsettings",
            name="celery_worker_concurrency",
            field=models.IntegerField(
                default=4,
                help_text="Number of concurrent Celery workers for translation tasks. Higher = faster translations but more CPU/memory usage. Recommended: 2x CPU cores for I/O-bound tasks. Requires worker restart to apply changes.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32),
                ],
                verbose_name="Translation Worker Concurrency",
            ),
        ),
    ]
